repository:
  name: asdf-shorebird
  description: shorebird plugin for the asdf version manager.
  topics: asdf-plugin

  private: false
  is_template: false
  default_branch: main

  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: false

  allow_auto_merge: true
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: true

labels:
  - name: bug
    color: '#cc0000'
    description: Something is broken
  - name: chore
    color: '#f2df8c'
    description: Repository or code maintenance
  - name: dependencies
    color: '#70f9e0'
    description: Update dependencies
  - name: documentation
    color: '#6cb524'
    description: Change in the documentation
  - name: feature
    color: '#336699'
    description: New functionality

teams:
  - name: developers
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: [ ]
          teams: [ ]
      required_status_checks:
        strict: true
        contexts:
          - Lint
          - Test
      enforce_admins: false
      required_linear_history: false
      required_conversation_resolution: true
      required_signatures: true
      restrictions:
        apps: [ ]
        users: [ ]
        teams: [ ]
